### ISSUE TITLE
Upgrade pippo version to latest

### ISSUE THREAD

**Issue by tjheslin1** [jonnymatts/JZONbie#2]
Currently Jzonbie's version of pippo is `1.1.0`.

Cant this be upgraded to the latest as I'm using pippo 1.5.0 and it is clashing with Jzonbie.

See the following error.

```java
java.lang.NoSuchFieldError: pippoSettings

	at ro.pippo.jetty.JettyServer.createDefaultSettings(JettyServer.java:94)
	at ro.pippo.jetty.JettyServer.createDefaultSettings(JettyServer.java:53)
	at ro.pippo.core.AbstractWebServer.getSettings(AbstractWebServer.java:44)
	at ro.pippo.core.WebServer.setPort(WebServer.java:124)
	at com.jonnymatts.jzonbie.Jzonbie.<init>(Jzonbie.java:53)
	at com.jonnymatts.jzonbie.junit.JzonbieRule.before(JzonbieRule.java:75)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by jonnymatts** [comment]
I have upgraded the pippo dependency to the latest version and found no problems when testing it with another project that uses pippo 1.5.0. You can find this fix in the 4.2 release.
